steps:
# Build Docker image: docker build -f Dockerfile -t gcr.io/my-project/my-image:latest .
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile', '-t', 'asia.gcr.io/hsgitlab-777/hellow-world:1.5', '.']

# Push to GCR: gcloud docker -- push gcr.io/my-project/my-image:latest
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/hsgitlab-777/hello-world:1.5']


# Connect to GCE server and pull new image
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', '$_SERVER', '--zone', '$_ZONE', '--command', 'docker pull asia.gcr.io/hsgitlab-777/hello-world:1.5']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', '$_SERVER', '--zone', '$_ZONE',  '--command', 'docker run --restart always --name hello-world -d -v /tmp:/tmp --log-driver=gcplogs asia.gcr.io/hsgitlab-777/hello-world:1.5']

substitutions:
  _SERVER: 'devops-gce'
  _ZONE: 'us-central1-c'
