steps:
## Build Docker image: docker build -f Dockerfile -t gcr.io/my-project/my-image:latest .
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-f', 'Dockerfile', '-t', 'asia.gcr.io/hsgitlab-777/hellow-world:latest', '.']
#
## Push to GCR: gcloud docker -- push gcr.io/my-project/my-image:latest
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['push', 'asia.gcr.io/hsgitlab-777/hello-world:latest']


# Connect to GCE server and pull new image
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', '$_SERVER', '--zone', '$_ZONE', '--command', 'docker pull asia.gcr.io/hsgitlab-777/hello-world']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', '$_SERVER', '--zone', '$_ZONE',  '--command',
         'docker run --name hello-world -v /tmp:/tmp -it asia.gcr.io/hsgitlab-777/hello-world /bin/bash -c "uwsgi --ini uwsgi_development.ini"']

substitutions:
  _SERVER: 'devops-gce'
  _ZONE: 'us-central1-c'

