version : '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /tmp:/tmp
    depends_on:
      - hello_world
  hello_world:
    build:
      dockerfile : Dockerfile
    volumes:
      - /tmp:/tmp
    command: uwsgi --ini uwsgi_development.ini